apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ci-limited-ref
  annotations:
    tcd/run-on-git-branches: >-
      ^test/.+$
    tcd/run-on-git-tags: >-
      ^v[0-9]+(\.[0-9]+){0,2}(\-.+)?$
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: checkout
            templateRef:
              name: git
              template: checkout

          - name: build-image
            depends: checkout
            templateRef:
              name: container
              template: build
            arguments:
              artifacts:
                - name: src
                  from: "{{tasks.checkout.outputs.artifacts.src}}"
              parameters:
                - name: registry
                  value: tcr.tks.trueidc.com/sandbox-private
