#################################################################
# Example: Build container image on specific git branch or tag
#
# tag v<semver>
#

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ci-dynamic-ref
  annotations:
    ## - Regular expression for allow git branch run workflow
    tcd/run-on-git-branches: >-
      ^test/.+$
    ## - Regular expressionfor allow git tag name to run workflow
    tcd/run-on-git-tags: >-
      ^v[0-9]+(\.[0-9]+){0,2}(\-.+)?$
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          ## - Checkout source on
          #    - branch test/*  Example test/dev  test/uat
          #    - tag v<semver>  Example v1.0.0 v1.0.0-rc.1
          - name: checkout
            # when: >-
            #   ( "{{workflow.parameters.git_ref_type}}" == "tag" && "{{workflow.parameters.git_ref_name}}" =~ "^v[0-9]+(\.[0-9]+){0,2}(\-.+)?$" )
            #   || ( "{{workflow.parameters.git_ref_type}}" == "branch" && "{{workflow.parameters.git_ref_name}}" =~ "^test\/.+$" )
            templateRef:
              name: git
              template: checkout

          ## - Build container image
          - name: build-image
            depends: checkout
            templateRef:
              name: container
              template: build
            arguments:
              artifacts:
                - name: src
                  from: "{{tasks.checkout.outputs.artifacts.src}}"
              parameters:
                - name: registry
                  value: tcr.tks.trueidc.com/sandbox-private


