#################################################################
# Example: Build container image on specific git branch or tag
#
# tag v<semver>
#

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ci-specific-ref
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: checkout
            ## - Build on
            #    - branch test/*  Example test/dev  test/uat
            #    - tag v<semver>  Example v1.0.0 v1.0.0-rc.1
            when: >-
              ( "{{workflow.parameters.git_ref_type}}" == "tag" && "{{workflow.parameters.git_ref_name}}" =~ "^v\d+(\.\d+){0,2}(\-.+)?$")
              || ("{{workflow.parameters.git_ref_type}}" == "branch" && "{{workflow.parameters.git_ref_name}}" =~ "^test\/.+$" )
            templateRef:
              name: git
              template: checkout

          - name: build-image
            depends: checkout.Succeeded
            templateRef:
              name: container
              template: build
            arguments:
              artifacts:
                - name: src
                  from: "{{tasks.checkout.outputs.artifacts.src}}"
              parameters:
                - name: registry
                  value: tcr.tks.trueidc.com/sandbox-private
