apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ci
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: checkout
            templateRef:
              name: git
              template: checkout
          - name: build-image
            depends: checkout.Succeeded
            templateRef:
              name: container
              template: build
            arguments:
              artifacts:
                - name: src
                  from: "{{tasks.checkout.outputs.artifacts.src}}"
              parameters:
                - name: registry
                  value: tcr.tks.trueidc.com/sandbox-private
