name: CI
on:
  push:
    #branches: [ "1.6" ]
    tags:
      - 'v*.*.*'
jobs:
  include:
    # needs: test
    name: Backend ci
    uses: tidc-cloud/devops-app-ci/.github/workflows/github-backend-ci-v2.yml@main
    with:
      image: ${GITHUB_REPOSITORY#tidc-cloud/core-cluster0-}